from fpdf import FPDF
import os

class StudentReportPDF(FPDF):
    def header(self):
        # Top branding bar
        self.set_fill_color(44, 62, 80) # Dark Navy
        self.rect(0, 0, 210, 40, 'F')
        
        # Header Title
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 20)
        self.cell(0, 15, 'STUDENT PERFORMANCE REPORT', ln=True, align='C')
        
        self.set_font('Helvetica', 'I', 10)
        self.cell(0, 5, 'AI-Powered Predictive Academic Analysis & Insights', ln=True, align='C')
        self.ln(15)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(127, 127, 127)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Student Performance Predictor System', 0, 0, 'C')

def generate_pdf_report(student_name, inputs, predicted_score, grade, risk_category, recommendations, output_dir="reports"):
    os.makedirs(output_dir, exist_ok=True)
    pdf_filename = f"{student_name.replace(' ', '_')}_Performance_Report.pdf"
    pdf_filepath = os.path.join(output_dir, pdf_filename)
    
    pdf = StudentReportPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    pdf.set_text_color(51, 51, 51)
    
    # Student Details Section
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 10, '1. Student Academic & Lifestyle Details', ln=True)
    pdf.set_draw_color(44, 62, 80)
    pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
    pdf.ln(5)
    
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(51, 51, 51)
    
    # Table of Inputs
    col_width = 95
    row_height = 7
    
    details = [
        ("Student Name:", str(student_name), "Previous Score:", f"{inputs['previous_score']}%"),
        ("Attendance:", f"{inputs['attendance']}%", "Study Hours/Day:", f"{inputs['study_hours']} hrs"),
        ("Assignments Completed:", f"{inputs['assignments_completed']}/10", "Class Participation:", f"{inputs['class_participation']}/5"),
        ("Sleep Hours/Day:", f"{inputs['sleep_hours']} hrs", "Screen Time/Day:", f"{inputs['screen_time']} hrs"),
        ("Physical Activity:", f"{inputs['physical_activity']}/5", "Parent Education:", str(inputs['parent_education'])),
        ("Family Income:", str(inputs['family_income']), "Internet Access:", str(inputs['internet_access'])),
        ("School Type:", str(inputs['school_type']), "", "")
    ]
    
    for row in details:
        if row[0]:
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(40, row_height, row[0], border=1)
            pdf.set_font('Helvetica', '', 10)
            pdf.cell(55, row_height, row[1], border=1)
        else:
            pdf.cell(95, row_height, "", border=0)
            
        if row[2]:
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(40, row_height, row[2], border=1)
            pdf.set_font('Helvetica', '', 10)
            pdf.cell(55, row_height, row[3], border=1)
        else:
            pdf.cell(95, row_height, "", border=0)
        pdf.ln()
        
    pdf.ln(8)
    
    # Prediction Results Section
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 10, '2. Performance Prediction & Risk Assessment', ln=True)
    pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
    pdf.ln(5)
    
    # Score Box
    pdf.set_fill_color(240, 244, 248)
    pdf.rect(pdf.get_x(), pdf.get_y(), 190, 25, 'F')
    
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(51, 51, 51)
    pdf.set_xy(pdf.get_x() + 5, pdf.get_y() + 5)
    pdf.cell(60, 15, f"Predicted Exam Score: {predicted_score}%", ln=False)
    pdf.cell(50, 15, f"Expected Grade: {grade}", ln=False)
    
    # Color code risk category
    if risk_category == "Low Risk":
        pdf.set_text_color(39, 174, 96) # Green
    elif risk_category == "Medium Risk":
        pdf.set_text_color(241, 196, 15) # Yellow
    else:
        pdf.set_text_color(192, 57, 43) # Red
        
    pdf.cell(70, 15, f"Academic Risk Level: {risk_category.upper()}", ln=True, align='R')
    pdf.set_text_color(51, 51, 51)
    pdf.ln(10)
    
    # AI Recommendations Section
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 10, '3. Dynamic AI Recommendations', ln=True)
    pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
    pdf.ln(5)
    
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(51, 51, 51)
    for rec in recommendations:
        pdf.cell(5, 6, chr(149), ln=False)
        pdf.multi_cell(185, 6, rec)
        pdf.ln(1)
        
    pdf.ln(10)
    
    # Disclaimer
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(127, 127, 127)
    pdf.multi_cell(0, 4, "Disclaimer: This analysis and prediction report is powered by machine learning algorithms based on historical student statistics. These results are indicators for proactive guidance and support, not absolute guarantees of academic outcomes.")
    
    pdf.output(pdf_filepath)
    return pdf_filepath
